// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc1qX0lVFErraCndNHqQUqDXVwlxrFo0w',
    appId: '1:557750885397:web:8cebb444e89f8d90ad021c',
    messagingSenderId: '557750885397',
    projectId: 'fir-training-14957',
    authDomain: 'fir-training-14957.firebaseapp.com',
    storageBucket: 'fir-training-14957.appspot.com',
    measurementId: 'G-QCBZNJPLDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_upeSirzPCxYq-R7t5sfUeS8X73Ur9oA',
    appId: '1:557750885397:android:5680014f48dedd35ad021c',
    messagingSenderId: '557750885397',
    projectId: 'fir-training-14957',
    storageBucket: 'fir-training-14957.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBseXPC50G589dYww3tUWQFVIgyrcz5948',
    appId: '1:557750885397:ios:3be8601ddf2404e5ad021c',
    messagingSenderId: '557750885397',
    projectId: 'fir-training-14957',
    storageBucket: 'fir-training-14957.appspot.com',
    iosBundleId: 'com.example.firforfir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBseXPC50G589dYww3tUWQFVIgyrcz5948',
    appId: '1:557750885397:ios:237f03f27cedb963ad021c',
    messagingSenderId: '557750885397',
    projectId: 'fir-training-14957',
    storageBucket: 'fir-training-14957.appspot.com',
    iosBundleId: 'com.example.firforfir.RunnerTests',
  );
}
